# Generated by Django 5.2.12 on 2026-03-14 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additionalwork',
            old_name='created_at',
            new_name='date_posted',
        ),
        migrations.AlterField(
            model_name='additionalwork',
            name='grade',
            field=models.CharField(choices=[('11', 'Grade 11'), ('12', 'Grade 12')], max_length=2),
        ),
    ]
