# Generated by Django 5.2.12 on 2026-03-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_quizresult_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=100)),
                ('grade', models.CharField(choices=[('11', '11'), ('12', '12')], max_length=2)),
                ('meeting_id', models.CharField(help_text='A unique name for the room', max_length=100, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
